### ISSUE TITLE
onChange event of Text input components do not work

### ISSUE THREAD

**Issue by devang9** [pnp/powerapps-designtoolkit#10]
I wrote a Set function on onChange event of Text input component but the code does not seem to execute on typing inside the textbox

**Comment by geoffroff** [comment]
Agreed missing from component
<pre>//////Customisations////////////////////////////////////////////////////////////
// Bug: missing txt_TextInput.OnChange action
////////////////////////////////////////////////////////////////////////////////
cmp_MD_Textinput.onChange()</pre>

**Comment by PowerRobin** [comment]
added in v1.0.0.8
