### ISSUE TITLE
textColorHex missing in OnStart

### ISSUE THREAD

**Issue by phil0074** [pnp/powerapps-designtoolkit#14]
After inserting cmp_MD_Navigation_Drawer component into Power App, there was a reference error. Found out that textColorHex not defined in second code block (i.e Set(defaults, Patch(defaults, {...}.

Added the following line and error is resolved:
`textColorHex: Match(JSON(defaults.textColor,IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch`

![image](https://user-images.githubusercontent.com/41122379/215886286-842488c1-fc7d-48bb-afda-b4b0fc6dcdbe.png)

**Comment by PowerRobin** [comment]
added textColorHex in Template v1.1
