### ISSUE TITLE
Text input component resizes

### ISSUE THREAD

**Issue by MarinaHadzi** [pnp/powerapps-designtoolkit#16]
Hi, 
on start of the template font size is defined (10) and then it is used in text input component but when I publish the app and run it or play it, text input increases its height so it becomes really big. So I figured out that if I just change Font size to 8 and then change it back to 10  this will be fixed.
![image](https://user-images.githubusercontent.com/71693895/217194975-c86dd423-7962-4a48-b0b0-84679110595f.png)
It is some kind of a bug

**Comment by PowerRobin** [comment]
Can't reproduce, probably fixed through a new PowerApps version
