### ISSUE TITLE
cmp_MD_Banner Action 2 On Select

### ISSUE THREAD

**Issue by geoffroff** [pnp/powerapps-designtoolkit#17]
Component cmp_MD_Banner action 2 button does not fire. Current custom property set to cmp_MD_Banner.action2Width rather than cmp_MD_Banner.action2OnSelect().

//////Customisations////////////////////////////////////////////////////////////
// Bug: btn_action2.OnSelect
// amend from cmp_MD_Banner.action2Width to cmp_MD_Banner.action2OnSelect()
////////////////////////////////////////////////////////////////////////////////
cmp_MD_Banner.action2OnSelect()

**Comment by PowerRobin** [comment]
Fixed bug in v1.0.0.8
