### ISSUE TITLE
cmp_MD_Textinput On Change Action Missing

### ISSUE THREAD

**Issue by geoffroff** [pnp/powerapps-designtoolkit#19]
On change action property missing.
<pre>//////Customisations////////////////////////////////////////////////////////////
// Bug: missing txt_TextInput.OnChange action
////////////////////////////////////////////////////////////////////////////////
cmp_MD_Textinput.onChange()</pre>

**Comment by PowerRobin** [comment]
Added OnSelect and OnChange for TextInput in v1.0.0.8
