### ISSUE TITLE
Name isn't valid. 'Transparent' isn't recognized.

### ISSUE THREAD

**Issue by vunguyen0104** [pnp/powerapps-designtoolkit#22]
Hi,

Importing MaterialDesignComponentLibrary_1_0_0_7.zip to my environment solution and use  MaterialDesignTemplate.msapp as starter template for my application, I inserted cmp_MD_AppBar_top component to my Home screen, ran App checker and got all the errors related to "Name isn't valid. 'Transparent' isn't recognized.". Because of that, all four icons of the top bar have back color as their background. Could you please provide some help with this issue?  

Please see attached image.
![MDK_PowerApps_Issue](https://user-images.githubusercontent.com/2191251/224156166-2c2198ed-3288-4acf-b98c-b14a5ea36f39.png)

Thank you,
Vu

**Comment by PowerRobin** [comment]
Fixed in v1.0.0.8 and Template v1.1

**Comment by vunguyen0104** [comment]
Thank you very much for your quick fixes. Really appreciate your help.
